// popular-trabel/src/components/ui/navbar/index.vue
<template lang="">
  <div class="bg-gray-600 px-10">
    <div class="w-[1200px] mx-auto flex justify-between items-center">
      <ul class="navbar">
        <li class="nav">Dashboard</li>
        <li class="nav">Master Price</li>
        <li class="nav">Custom Price</li>
        <li class="nav">Calendar</li>
        <li class="nav">Reports</li>
      </ul>
      <div>
        <div class="w-10 h-10 border border-white rounded-full"></div>
      </div>
    </div>
  </div>
</template>
<script>
export default {};
</script>
<style scoped>
.navbar {
  @apply flex space-x-8 text-white py-4;
}
.nav {
  @apply text-lg;
}
</style>

// src/components/Navbar/Navbar.jsx
import { CgProfile } from "react-icons/cg";
import { GoBell } from "react-icons/go";

const Navbar = () => {
  return (
    <div className="bg-[#0f0838]">
      <div className="container mx-auto flex justify-between px-10 py-5">
        {/* nav manu */}
        <div>
          <ul className="flex capitalize gap-10 text-white ">
            <li>dashboard</li>
            <li>master price</li>
            <li>custom price</li>
            <li>calender</li>
            <li>reports</li>
          </ul>
        </div>
        {/* profile and notification */}
        <div>
          <div className="flex gap-2 items-center text-white">
            <GoBell className="text-lg" />
            <CgProfile className="text-2xl" />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Navbar;
